### PR TITLE
Assignment: week 1 - Shashank

### PR DESCRIPTION
**Pull request by shashankvineet**
3 of the URLs in the week1-shashank folder don't exist anymore. The links pointed to webpages that weren't found (resulting in 404 not found errors when I even tried opening them in the browser). They were:

1. http://ajw.asahi.com/article/asia/korean_peninsula/AJ201403240051
2. http://americafolks.com/index.php/2017/03/11/north-korea-to-launch-devastating-missile-attack-in-direct-threat-to-next-us-president/
3. http://americaninnorthkorea.com/2013/05/29/american-g-i-clown-at-the-pyongyang-military-circus

Lastly, one URL had an issue of: HTML not found
https://www.usnews.com/news/politics/articles/2020-04-21/china-south-korea-dispute-reports-on-health-of-north-korean-leader-kim-jong-un

### CODE REVIEW

**Comment by mikeizbicki** [comment]
I currently can't merge your work due to the merge conflicts in the `tests/golden.csv` file.

The problem is that you have changed the date formats throughout each of the files.  They must all be in `YYYY-MM-DD` format, but you have changed it to `M/D/YY` format.  Probably excel did this for you automatically, and you will have to disable this conversion.

This change creates two problems:

1. It creates the merge conflicts because you are editing lines that other people are also working on.

2. The test cases rely on the dates being in `YYYY-MM-DD` format, and so the test cases no longer work, even for the previously completed lines.  If you notice on travis, all test cases are failing now.

So your next task is to covert these dates back into the correct format.  It would be particularly helpful if you could do this in a single commit.

**Comment by shashankvineet** [comment]
I tried fixing the date and time problems by changing some of the excel formatting as well as running test_golden.py with new xpaths, but as per Travis, the test_golden.py  is giving me FileNotFoundError errors for most of the URLs because it's not able to find them in the .cache file. Any idea what must be going wrong?

**Comment by mikeizbicki** [comment]
Your `tests/golden.csv` file still has the wrong date formats inside of it.  You fixed it in e0438f2  but then reverted to the old format in b2deb5d.

The `date_downloaded` field is used when fetching the file from the cache, and so if this field is wrong, it won't be able to retrieve the html.

**Comment by mikeizbicki** [comment]
I'm closing this pull request for now, reopen it when you want me to look at it again.

**Pull request closed without merging**
