### PR TITLE
Added support for: Maxine Baghdadi

### PR DESCRIPTION
**Pull request by maxinebaghdadi**
https://abc14news.com/2020/04/21/during-the-coronavirus-crisis-how-is-north-korea-really-handling-its-zero-cases/ : Site can't be found

https://finance.yahoo.com/news/u-stock-futures-dip-news-032407918.html : Doesn't Exist

https://finance.yahoo.com/news/kim-condition-critical-surgery-u-030450580.html : Doesn't Exist

### CODE REVIEW

**Comment by mikeizbicki** [comment]
I don't see any changes to the `metahtml/timestamp.py` file in your commit.  Is that correct?

**Comment by mikeizbicki** [comment]
Running the tests on a cloned version of your repo, I get 86 failures.  I think this is a combination of the previously passing test failing due to your changes in `golden.csv`, and that your changes to `timestamp.py` are not uploaded.

**Comment by maxinebaghdadi** [comment]
Hi Professor Izbicki, 

When I run pytest on my terminal, I'm getting 22 failures. Is that what you see now? I'll try to debug the remaining 22. 

Thanks,
Maxine

**Comment by mikeizbicki** [comment]
I don't see any new commits uploaded, so my results are still the same as before.

**Pull request closed without merging**
