### PR TITLE
Assignment: week 1 - Shashank (fixed)

### PR DESCRIPTION
**Pull request by shashankvineet**
It finally looks like all the URLs I worked on this week now seem to pass the test cases. 

Same as before, the following URLs don't exist anymore, which is to say that they give error 404 not found messages or that HTML is not found. 

https://www.usnews.com/news/politics/articles/2020-04-21/china-south-korea-dispute-reports-on-health-of-north-korean-leader-kim-jong-un

http://123filmz.blogspot.com/2014/12/sony-pictures-hacked-possibility-that.html

http://americaninnorthkorea.com/2013/05/29/american-g-i-clown-at-the-pyongyang-military-circus

http://americafolks.com/index.php/2017/03/11/north-korea-to-launch-devastating-missile-attack-in-direct-threat-to-next-us-president/

http://ajw.asahi.com/article/asia/korean_peninsula/AJ201403240051

### CODE REVIEW

**Comment by mikeizbicki** [comment]
When I run the test cases, I get 51 failed tests.  It looks like most of these tests are tests that I previously had passing, but are no longer passing.

Somehow in your formatting, the hh:mm:ss sections got deleted in lots of these test cases and replaced by 00:00:00, and this is what's causing the tests to fail.  If you run the following command,
```
$ git diff 03521850cede9d543ca5c15b6e078a721ebc6c15:tests/golden.csv tests/golden.csv
```
it will show all the changes you've made to the csv file, and the red lines in particular show that you've replaced several good test cases with test cases that now fail.

I'm happy to walk you through this on zoom if you'd like.

**Comment by shashankvineet** [comment]
Are you on zoom now?

**Comment by shashankvineet** [comment]
I tried running 

```
git diff 03521850cede9d543ca5c15b6e078a721ebc6c15:tests/golden.csv tests/golden.csv
```

but it gives me the following error:

```
fatal: Path 'tests/golden.csv' exists on disk, but not in '03521850cede9d543ca5c15b6e078a721ebc6c15'.
```

What would be the best way for me to revert the changes that got applied to the URLs you had worked on?

**Comment by mikeizbicki** [comment]
We'll probably need to look at it in zoom together.  I'll be on zoom in the
morning tomorrow from about 8-9 with other students, and I can meet with you
after them, or I can meet in the afternoon around 2.

**Comment by shashankvineet** [comment]
I can do around 9 tomorrow. See you then!

**Comment by shashankvineet** [comment]
Can we actually do the 2pm call instead? Something came up now that I have to attend to.

**Pull request closed without merging**
