### PR TITLE
Week 1 Assignment

### PR DESCRIPTION
**Pull request by selina-28030**
bloomberg.com note: thinks I'm a robot

krdo.com note: article no longer available, could not be entered in csv, used another article

latest-today-news.com note: redirects to home page when opening the url, only extracts published date for the csv file. added another valid article which extracts both published and updated date

localnews8.com note: article beginning with "US Source" is now "Page not found", the other article works

naijawaves.com note: article beginning with "Kim Jong Un's Health" is now "Page not found", added another article which works

networkaggregation.com note: account suspended

newzandar.com note: both articles redirect to home page when opening the url, extracts published date for the csv file, but title is just the website name, added another article which added title/published and updated date

presstories.com note: redirects to home page when opening the url, extracts date for the csv file, but title is just the website name, added another article which works fine

ussanews.com note: both url links to other articles entirely, title and updated date are of the redirected articles

worldnewsking.com note: account suspended

### CODE REVIEW

**Comment by mikeizbicki** [comment]
Great job, thanks!

I've scanned through your changes and they look good overall.  I'll manually fix the issues you pointed out.

There's one more change I'd like you to make though.  In your version of the csv file, you've added a `,` after each line (probably excel did this for you?); this makes the git diff difficult to read because it shows that all lines have been changed, and so I can't easily see just your actual changes.  Can you fix this so that these trailing commas are removed?  If you run the command
```
$ git diff --minimal 03521850cede9d543ca5c15b6e078a721ebc6c15:tests/golden.csv tests/golden.csv
```
most of the output should be white with only a small amount of green for your changes.

**Comment by selina-28030** [comment]
I've been using libreoffice, would you happen to know how that might have happened?

**Comment by selina-28030** [comment]
It should be fixed!

**Comment by mikeizbicki** [comment]
I've incorporated the you've made and fixed the code so that it works for the problematic hostnames you identified.  Thanks!

I can't merge the pull request directly because you have many different commits, and so I've manually squashed your commits into a single commit.  Even though it will say that the pull request is closed, all your changes are added into the repo and if you look at https://github.com/mikeizbicki/metahtml/graphs/contributors you've been given credit for the changes.

**Comment by mikeizbicki** [comment]
Whoops, one last thing I forgot to mention.  The website https://www.cbsnews.com/news/kim-jong-un-north-korea-south-korea-no-unusual-developments-reports-kims-health-today-2020-04-21/ that you did had the wrong date associated with it, so I had to redo that one.  The python code was putting a date into the csv file based on the url of the webpage, but there was a more detailed date in the webpage that also included a time that you didn't catch.

**Pull request closed without merging**
